import json
import pprint

data = {
    'Sample': ['hello', 'world', 'python', 'coding', 'women'],
    'Easy' : ['Beekeeper',
            'Rogue',
            'Icy',
            'Dryness',
            'Attack',
            'Tolstoy',
            'Does',
            'Arc',
            'Pyramid',
            'Dot',
            'Kite',
            'Oval',
            'Prism',
            'Sector',
            'Triangle',
            'Atlas',
            'Roman',
            'Green',
            'Greek',
            'Reddish',
            'Star',
            'Round',
            'Point',
            'Plane',
            'Line',
            'Interval',
            'Eclipse',
            'Disk',
            'Acute',
            'Biology',
            'Jiffy',
            'Igloo',
            'Quill',
            'Black',
            'Mystify',
            'Disc',
            'Heart',
            'Exodus',
            'God',
            'Toy',
            'Windy',
            'Cycle',
            'Party',
            'Fish',
            'Animal',
            'Pet',
            'Fake',
            'Brick',
            'Fly',
            'Airplane'],
    'Difficult' : ['Crypt',
            'Encrypt',
            'Decrypt',
            'Dwarves',
            'Gazebo',
            'Kiosk',
            'Haiku',
            'Buzzard',
            'Glowworm',
            'Kilobyte',
            'Stronghold',
            'Syndrome',
            'Shiva',
            'Shiv',
            'Wimpy',
            'Zeal',
            'Zilch',
            'Zipper',
            'Topaz',
            'Naphtha',
            'Kiwi',
            'Kiwifruit',
            'Fuchsia',
            'Equip',
            'Foxtrot',
            'Calligraphy',
            'Abyss',
            'Askew',
            'Axiom',
            'Cockiness',
            'Cobweb',
            'Soapy',
            'Avenue',
            'Daiquiri',
            'espionage',
            'Boxcar'],
    'Random' : ['Cobweb',
            'Orgy',
            'Buxom',
            'Boggle',
            'Fishhook',
            'Flopping',
            'Galvanize',
            'Embezzle',
            'Glyph',
            'Ivy',
            'Dizzying',
            'Bastard',
            'Damn',
            'Bugger',
            'Gross',
            'Fuzz',
            'Fervid',
            'Memento',
            'Momentum',
            'Quad',
            'Hardcore',
            'Waxy',
            'Yacht',
            'Zealous',
            'Wildebeest',
            'Toady',
            'Pixel',
            'Memory',
            'Neighborhood',
            'Palace',
            'Zoo',
            'Fetish',
            'Quirk',
            'University',
            'Poetry',
            'Write',
            'Plates',
            'Norway',
            'Uganda',
            'Djibouti',
            'Canal',
            'Mill',
            'Crossword',
            'CrossFit',
            'Zumba',
            'Dumbly',
            'Dumbbell',
            'Philadelphia'],
    'Animals' : ['panda',
            'cat',
            'moth',
            'moose',
            'buffalo',
            'caterpillar',
            'albatross',
            'duck',
            'mouse',
            'salamander',
            'goose',
            'rat',
            'aardvark',
            'joey',
            'robin',
            'horse',
            'koala',
            'bear',
            'hippopotamus',
            'camel',
            'cougar',
            'giraffe',
            'eagle',
            'crocodile',
            'dog',
            'bird',
            'penguin',
            'pony',
            'bat',
            'otter',
            'porcupine',
            'dolphin',
            'hamster',
            'chameleon',
            'swordfish',
            'groundhog',
            'cricket',
            'clownfish',
            'leopard',
            'rabbit',
            'buffalo',
            'shark',
            'stallion',
            'wombat',
            'kitten',
            'reindeer',
            'wolf',
            'dragon',
            'whale',
            'hyena',
            'unicorn',
            'tuna',
            'platypus',
            'shrimp',
            'skunk',
            'bulldog',
            'ladybug',
            'beaver',
            'puppy',
            'weasel',
            'owl',
            'chipmunk',
            'lamb',
            'tiger',
            'doe',
            'ewe',
            'pelican',
            'ape',
            'partridge',
            'hedgehog',
            'cow',
            'spider',
            'turtle',
            'alligator',
            'seahorse',
            'llama',
            'hive',
            'lion',
            'armadillo',
            'herd',
            'gopher',
            'elk',
            'fox',
            'guineapig',
            'sealion',
            'donkey',
            'frog',
            'crow',
            'zebra',
            'toad',
            'worm',
            'panther',
            'chinchilla',
            'flock',
            'chimpanzee',
            'calf',
            'warthog',
            'cub',
            'seagull',
            'parakeet',
            'chicken',
            'human',
            'toucan',
            'deer',
            'lobster',
            'dove',
            'walrus',
            'jellyfish',
            'crab',
            'tortoise',
            'duckling',
            'wasp',
            'squirrel',
            'wildebeest',
            'catfish'],
    'Science' : ['astrophysics', 'astronomy', 'atom',	'beaker',	'biochemistry',	'biology',
                'botany',	'burette',	'cell',	'chemical',	'chemistry',	'climate',
                'climatologist',	'control',	'cuvette',	'data',	'datum',	'electricity',
                'electrochemist',	'element',	'energy',	'entomology',	'evolution',	'experiment',
                'fact',	'flask',	'fossil',	'funnel',	'genetics',	'geology',
                'geophysics',	'glassware',	'gravity',	'herpetology',	'hypothesis',	'ichthyology',
                'immunology',	'lab',	'laboratory',	'laws',	'magnetism',	'mass',
                'matter',	'measure',	'meteorologist',	'meteorology',	'microbiologist',	'microbiology',
                'microscope',	'mineral',	'molecule',	'motion',	'observe',	'observatory',
                'organism',	'ornithology',	'particle',	'physics',	'pipette',	'seismology',
                'radiology',	'research',	'retort',	'scale',	'science',	'scientist',
                'telescope',	'volcanology',	'volume',	'anthropology',	'archaeology',	'astronomy',
                'temperature',	'theory',	'thermometer',	'tissue',	'variable',	'virologist',
                'weather',	'weigh',	'zoology',	'aerodynamics',	'agronomy',	'anatomy',
                'bacteriology',	'biochemistry',	'biology',	'biophysics',	'botany',	'cartography',
                'chemistry',	'climatology',	'cosmology',	'criminology',	'ergonomics',	'ethnology',
                'dermatology',	'ecology',	'economics',	'embryology',	'entomology',	'epidemiology',
                'forestry',	'genetics',	'genomics',	'geology',	'geophysics',	'hydrology',
                'gerontology',	'glaciology',	'hematology',	'herpetology',	'histology',	'horticulture',
                'immunology',	'mineralology',	'morphology',	'neurology',	'paleontology',	'radiology',
                'kinesiology',	'linguistics',	'mechanics',	'metallurgy',	'meteorology',	'microbiology',
                'neuroscience',	'nutrition',	'oceanography',	'oncology',	'optics',	'ornithology',
                'parasitology',	'pathology',	'petrology',	'physics',	'physiology',	'psychology',
                'robotics',	'seismology',	'sociobiology',	'sociology',	'xenobiology',	'observation',
                'taxonomy',	'tectonics',	'thermodynamics',	'toxicology',	'virology',	'volcanology']
}

def write_data(words):
    with open('hangman_words.json', 'w') as file:
        json.dump(words, file)

# write_data(data)

def load_data():
    with open ('hangman_words.json') as file:
        data = json.load(file)
    return data

quiz_words = load_data()
# pprint.pprint(quiz_words)

a = quiz_words['Animals']
print(len(a))